"""add unique constraints for favorite and thread

Revision ID: 4f8ed00ffb43
Revises: 0f3ee3b1d6b5
Create Date: 2026-03-18 20:35:21.227177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8ed00ffb43'
down_revision: Union[str, Sequence[str], None] = '0f3ee3b1d6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_favorite_user_listing', 'favorite', ['user_id', 'listing_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_favorite_user_listing', 'favorite', type_='unique')
    # ### end Alembic commands ###
